goods_map/stock/urls.py
from django.urls import path
from goods_map.stock.views import StockHome

urlpatterns = [
    path('', StockHome.as_view(), name='stock_home'),
]

goods_map/urls.py
from django.contrib import admin
from django.urls import path, include

from goods_map import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home_page'),
    path('stock/', include('goods_map.stock.urls')),
    path('count/', include('goods_map.count.urls')),
    path('goods/', include('goods_map.goods.urls')),
    path('image/', include('goods_map.gallery.urls')),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

goods_map/goods/models.py
from django.db import modelsfrom goods_map.stock.models import StockModel, StoreHall, StoreBack, StoreUpclass GoodsModel(models.Model):    name = models.CharField(max_length=50)    cost_price = models.PositiveSmallIntegerField(null=True)    wholesale_price = models.PositiveSmallIntegerField(null=True)    retail_price = models.PositiveSmallIntegerField(null=True)    weight = models.FloatField(null=True)    store_hall = models.ForeignKey(StoreHall, on_delete=models.PROTECT,                                   related_name='store_hall', null=True)    store_back = models.ForeignKey(StoreBack, on_delete=models.PROTECT,                                   related_name='store_back', null=True)    store_up = models.ForeignKey(StoreUp, on_delete=models.PROTECT,                                 related_name='store_up', null=True)    stock = models.ManyToManyField(StockModel)    def __str__(self):        return self.name

goods_map/stock/models.py
from django.db import models


class StockModel(models.Model):
    name = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.name


class StoreHall(models.Model):
    name = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.name


class StoreBack(models.Model):
    name = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.name


class StoreUp(models.Model):
    name = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.name

goods_map/stock/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from goods_map.stock import models


class StockHome(LoginRequiredMixin, ListView):
    template_name = 'stock.html'
    model = models.StockModel

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['store_hall'] = models.StoreHall.objects.all()
        context['store_back'] = models.StoreBack.objects.all()
        context['store_up'] = models.StoreUp.objects.all()
        return context

goods_map/stock/templates/stock.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block main %}
<h1>Stock</h1>


{% if store_hall %}
<h2>Goods list in Store</h2>
<ul>
    {% for storage in store_hall %}
    <li>{{ storage }}</li>
        <ul>
            {% for product in storage.store_hall.all %}
            <li>
                <a href="{% url 'good_card' product.id %}"> {{ product }}</a>
            </li>
            {% endfor %}
        </ul>


    {% endfor %}
</ul>
{% endif %}


{% if store_hall %}
<h2>Goods list in Back</h2>
<ul>
    {% for storage in store_back %}
    <li>{{ storage }}</li>
        <ul>
            {% for product in storage.store_back.all %}
            <li>
                <a href="{% url 'good_card' product.id %}"> {{ product }}</a>
            </li>
            {% endfor %}
        </ul>
    {% endfor %}
</ul>
{% endif %}


{% if store_hall %}
<h2>Goods list in second floor</h2>
<ul>
    {% for storage in store_up %}
    <li>{{ storage }}</li>
        <ul>
            {% for product in storage.store_up.all %}
            <li>
                <a href="{% url 'good_card' product.id %}"> {{ product }}</a>
            </li>
            {% endfor %}
        </ul>
    {% endfor %}
</ul>
{% endif %}


<!--<h2>Goods list in stock</h2>-->
<!--<ul>-->
<!--    {% for i in object_list %}-->
<!--    <li>{{ i }}</li>-->
<!--        <ul>-->
<!--            {% for w in i.goodsmodel_set.all %}-->
<!--            <li>-->
<!--                <a href="{% url 'good_card' w.id %}"> {{ w }}</a>-->
<!--            </li>-->
<!--            {% endfor %}-->
<!--        </ul>-->
<!--    {% endfor %}-->
<!--</ul>-->
<!---->
<!---->
{% endblock%}