goods_map/goods/urls.py
from django.urls import path
from goods_map.goods import views


urlpatterns = [
    path('', views.GoodsList.as_view(), name='good_list'),
    path('create/', views.CreateGood.as_view(), name='create_good'),
    path('<int:pk>/update/', views.UpdateGood.as_view(), name='update_good'),
    path('<int:pk>/delete/', views.DeleteGood.as_view(), name='delete_good'),
    path('<int:pk>/add_storage/',
         views.UpdateStorage.as_view(), name='add_storage'),
    path('<int:pk>/', views.GoodCard.as_view(), name='good_card'),
]

goods_map/urls.py
from django.contrib import admin
from django.urls import path, include

from goods_map import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home_page'),
    path('stock/', include('goods_map.stock.urls')),
    path('count/', include('goods_map.count.urls')),
    path('goods/', include('goods_map.goods.urls')),
    path('image/', include('goods_map.gallery.urls')),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

goods_map/count/models.py
from django.db import models
from goods_map.goods.models import GoodsModel


class CountGoods(models.Model):
    datetime = models.DateField(auto_now=True)
    count = models.PositiveSmallIntegerField()
    good_id = models.ForeignKey(GoodsModel, on_delete=models.CASCADE)
    cost_price = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.good_id

goods_map/gallery/models.py
from django.db import models
from goods_map.goods.models import GoodsModel


class ImageModel(models.Model):
    product_id = models.ForeignKey(GoodsModel, on_delete=models.CASCADE)
    images = models.ImageField()

    def __str__(self):
        return self.images

goods_map/goods/models.py
from django.db import modelsfrom goods_map.stock.models import StockModel, StoreHall, StoreBack, StoreUpclass GoodsModel(models.Model):    name = models.CharField(max_length=50)    cost_price = models.PositiveSmallIntegerField(null=True)    wholesale_price = models.PositiveSmallIntegerField(null=True)    retail_price = models.PositiveSmallIntegerField(null=True)    weight = models.FloatField(null=True)    store_hall = models.ForeignKey(StoreHall, on_delete=models.PROTECT,                                   related_name='store_hall', null=True)    store_back = models.ForeignKey(StoreBack, on_delete=models.PROTECT,                                   related_name='store_back', null=True)    store_up = models.ForeignKey(StoreUp, on_delete=models.PROTECT,                                 related_name='store_up', null=True)    stock = models.ManyToManyField(StockModel)    def __str__(self):        return self.name

goods_map/goods/forms.py
from django import forms
from goods_map.goods.models import GoodsModel
from goods_map.stock import models


class GoodsForm(forms.ModelForm):
    name = forms.CharField(
        max_length=50, label='Name',
        widget=forms.TextInput(
            attrs={'id': 'id_name',
                   'class': 'form-control mb-3',
                   'placeholder': 'Name'}))

    cost_price = forms.IntegerField(
        label='Cost price',
        required=False,
        widget=forms.TextInput(
            attrs={'id': 'id_cost_price',
                   'class': 'form-control mb-3',
                   'placeholder': 'Write cost price'}))

    wholesale_price = forms.IntegerField(
        label='Wholesale price',
        # required=False,
        widget=forms.TextInput(
            attrs={'id': 'id_wholesale_price',
                   'class': 'form-control mb-3',
                   'placeholder': 'Write Wholesale price'}))

    retail_price = forms.IntegerField(
        label='Retail price',
        required=False,
        widget=forms.TextInput(
            attrs={'id': 'id_retail_price',
                   'class': 'form-control mb-3',
                   'placeholder': 'Write Retail price'}))

    weight = forms.FloatField(
        label='Weight',
        required=False,
        widget=forms.TextInput(
            attrs={'id': 'id_retail_price',
                   'class': 'form-control mb-3',
                   'placeholder': 'Write weight of bag'}))
    store_hall = forms.ModelChoiceField(
        queryset=models.StoreHall.objects.all(), label='Store hall',
        required=False,
        widget=forms.Select(
            attrs={'id': 'id_store_hall',
                   'class': 'form-select mb-3'}))

    store_back = forms.ModelChoiceField(
        queryset=models.StoreBack.objects.all(), label='Store back',
        required=False,
        widget=forms.Select(
            attrs={'id': 'id_store_back',
                   'class': 'form-select mb-3'}))

    store_up = forms.ModelChoiceField(
        queryset=models.StoreUp.objects.all(), label='Store up',
        required=False,
        widget=forms.Select(
            attrs={'id': 'id_store_up',
                   'class': 'form-select mb-3'}))

    stock = forms.ModelMultipleChoiceField(
        queryset=models.StockModel.objects.all(), label='Stock',
        required=False,
        widget=forms.SelectMultiple(attrs={'id': 'id_labels',
                                           'class': 'form-select mb-3'}))

    class Meta:
        model = GoodsModel
        fields = ['name',
                  'cost_price',
                  'wholesale_price',
                  'retail_price',
                  'weight',
                  'store_hall',
                  'store_back',
                  'store_up',
                  'stock'
                  ]


class Storage(forms.ModelForm):
    store_hall = forms.ModelChoiceField(
        queryset=models.StoreHall.objects.all(), label='Store hall',
        required=False,
        widget=forms.Select(
            attrs={'id': 'id_store_hall',
                   'class': 'form-select mb-3'}))

    store_back = forms.ModelChoiceField(
        queryset=models.StoreBack.objects.all(), label='Store back',
        required=False,
        widget=forms.Select(
            attrs={'id': 'id_store_back',
                   'class': 'form-select mb-3'}))

    store_up = forms.ModelChoiceField(
        queryset=models.StoreUp.objects.all(), label='Store up',
        required=False,
        widget=forms.Select(
            attrs={'id': 'id_store_up',
                   'class': 'form-select mb-3'}))

    stock = forms.ModelMultipleChoiceField(
        queryset=models.StockModel.objects.all(), label='Stock',
        required=False,
        widget=forms.SelectMultiple(attrs={'id': 'id_labels',
                                           'class': 'form-select mb-3'}))

    class Meta:
        model = GoodsModel
        fields = [
            'store_hall',
            'store_back',
            'store_up',
            'stock'
            ]

goods_map/goods/views.py
import math
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (CreateView,
                                  UpdateView,
                                  DeleteView,
                                  DetailView)

from goods_map.forms import FilterForm
from goods_map.goods.models import GoodsModel
from goods_map.goods.forms import GoodsForm, Storage
from django.urls import reverse_lazy
from django_filters.views import FilterView

from goods_map.mixin import AdminMixin


class GoodsList(LoginRequiredMixin, FilterView):
    paginate_by = 5
    template_name = 'goods_list.html'
    model = GoodsModel
    filterset_class = FilterForm


class CreateGood(AdminMixin, CreateView):
    template_name = 'edit.html'
    model = GoodsModel
    form_class = GoodsForm
    success_url = reverse_lazy('home_page')
    extra_context = {'title': 'Create Good', 'button': 'Create'}

    def form_valid(self, form):

        if not form.instance.wholesale_price:
            weight = form.instance.weight if form.instance.weight else 1
            form.instance.wholesale_price = math.ceil(
                (form.instance.cost_price * 0.27) + (weight * 6) + 2)
        if not form.instance.retail_price:
            form.instance.retail_price = form.instance.wholesale_price + 7

        form.save()
        return super().form_valid(form)


class UpdateGood(AdminMixin, UpdateView):
    template_name = 'edit.html'
    model = GoodsModel
    form_class = GoodsForm
    success_url = reverse_lazy('home_page')
    extra_context = {'title': 'Update Good', 'button': 'Update'}


class DeleteGood(AdminMixin, DeleteView):
    template_name = 'delete.html'
    model = GoodsModel
    success_url = reverse_lazy('good_list')


class GoodCard(LoginRequiredMixin, DetailView):
    template_name = 'good_card.html'
    model = GoodsModel


class UpdateStorage(LoginRequiredMixin, UpdateView):
    template_name = 'edit.html'
    model = GoodsModel
    form_class = Storage
    success_url = reverse_lazy('home_page')
    extra_context = {'title': 'Update Storage', 'button': 'Update'}

goods_map/goods/templates/good_card.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}


{% block main %}


<div class="card">
    <div class="card-header bg-light text-black">
        <div class="nav-item d-flex justify-content-sm-between w-100">
            <div class="d-flex">
                <h1 class="mb-4">{{ object }}</h1>
            </div>
            {% if request.user.is_superuser %}
            <div class="d-flex row p-1">
                <button class="btn btn-primary mb-1">
                    <a class="text-white text-decoration-none" href="{% url 'update_good' pk=object.id %}">Update</a>
                </button>
                <button class="btn btn-danger mb-1">
                    <a class="text-white text-decoration-none" href="{% url 'delete_good' pk=object.id %}">Delete</a>
                </button>
            </div>
            {% endif %}
        </div>
    </div>
    {% if request.user.is_superuser %}
    <div>
        <button class="btn btn-success mb-1">
            <a class="text-white text-decoration-none" href="{% url 'add_image' pk=object.id %}">Add Foto</a>
        </button>
    </div>
    {% endif %}
    <div class="col" >
        {% if object.imagemodel_set.all %}
        {% for i in object.imagemodel_set.all %}
        <a href="{{ i.images.url }}">
            <img src="{{ i.images.url }}" class="rounded d-block mx-auto" alt="Responsive image" style="max-height:250px">
        </a>
        {% endfor %}
        {% else %}
        <div>
            <img src="{% static 'goods_map/image_not_found.png' %}" class="rounded d-block mx-auto" alt="Responsive image" style="max-height:250px">
        </div>
        {% endif %}
    </div>

    <div class="card-body bg-light">
        <hr>

        <div class="container">
            <div class="row p-1">

                <div class="col">
                    Cost price
                </div>

                <div class="col">
                    {% if object.cost_price %}
                    {{ object.cost_price }} ¥
                    {% else %}
                    ---
                    {% endif %}
                </div>
            </div>

            <div class="row p-1">

                <div class="col">
                    Wholesale price
                </div>

                <div class="col">
                    {% if object.wholesale_price %}
                    {{ object.wholesale_price }} ₼
                    {% else %}
                    ---
                    {% endif %}

                </div>
            </div>

            <div class="row p-1">

                <div class="col">
                    Retail price
                </div>

                <div class="col">
                    {% if object.retail_price %}
                    {{ object.retail_price }} ₼
                    {% else %}
                    ---
                    {% endif %}
                </div>
            </div>

            <div class="row p-1">

                <div class="col">
                    Weight
                </div>

                <div class="col">
                    {% if object.weight %}
                    {{ object.weight }} kg
                    {% else %}
                    ---
                    {% endif %}
                </div>
            </div>

            <hr>

            <div class="row p-1">
                <div class="col">
                    Market stock
                </div>

                <div class="col">
                    {% if object.store_hall or object.store_back or object.store_up %}
                        <div class="col">
                            {% if object.store_hall %}
                                {{ object.store_hall }}
                            {% endif %}
                        </div>
                        <div class="col">
                            {% if object.store_back %}
                                {{ object.store_back }}
                            {% endif %}
                        </div>
                        <div class="col">
                            {% if object.store_up %}
                                {{ object.store_up }}
                            {% endif %}
                        </div>

                    {% else %}
                    ---
                    {% endif %}
                    <hr>
                </div>
            </div>


            <div class="row p-1">
                <div class="col">
                    Store stock
                </div>

                <div class="col">
                    {% if object.stock.all %}
                    {% for i in object.stock.all %}
                    {{ i }}
                    {% endfor %}
                    {% else %}
                    ---
                    {% endif %}
                </div>
            </div>
            <div class="d-flex justify-content-end">
                <button class="btn btn-primary mb-3">
                    <a class="text-white text-decoration-none" href="{% url 'add_storage' object.id %}">Change storage</a>
                </button>
            </div>



            <hr>
            <div class="row p-1">

                <div class="col">
                    Order info
                </div>

                <div class="col">
                    <dl class="row p-1">
                        <dt class="col">Date</dt>
                        <dt class="col"> Count</dt>
                        <dt class="col">Cost price</dt>
                        <dt class="col"></dt>
                    </dl>



                    {% for i in object.countgoods_set.all %}
                    <dl class="row p-0.5">
                        <dd class="col">{{ i.datetime }}</dd>
                        <dd class="col">{{ i.count }}</dd>
                        <dd class="col">{{ i.cost_price }} ¥</dd>
                        <dd class="col">
                            <a href="{% url 'update_count' pk=object.id %}">Update</a>
                            <a href="{% url 'update_count' pk=object.id %}">Delete</a>
                        </dd>
                    </dl>
                    {% endfor %}
                </div>
            </div>

            {% if request.user.is_superuser %}
                <div class="d-flex justify-content-end">
                    <button class="btn btn-primary mb-3">
                        <a class="text-white text-decoration-none" href="{% url 'add_goods' pk=object.id %}">Add count</a>
                    </button>
                </div>

            {% endif %}
        </div>
    </div>
</div>


{% endblock%}

goods_map/goods/templates/goods_list.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}


{% block main %}

<div class="container">
    {% if object_list %}
        {% for good in object_list %}
        <a href="{% url 'good_card' pk=good.id %}" class="text-black text-decoration-none"><div class="row align-items-center">
            <div class="col" >
                {% if good.imagemodel_set.all %}
                {% for i in good.imagemodel_set.all %}
                <img src="{{ i.images.url }}" class="rounded float-left" alt="{{ i.images }}" style="max-height:150px">

                {% endfor %}
                {% else %}
                <img src="{% static 'goods_map/image_not_found.png' %}" class="rounded float-left" alt="Responsive image" style="max-height:150px">
                {% endif %}
            </div>
            <div class="col">
                <div class="row p-1">

                    <div class="col">
                        Name
                    </div>

                    <div class="col">
                        {{ good.name }}
                    </div>
                </div>
                <div class="row p-1">

                    <div class="col">
                        Wholesale price
                    </div>

                    <div class="col">
                        {% if good.wholesale_price %}
                        {{ good.wholesale_price }} ₼
                        {% else %}
                        ---
                        {% endif %}

                    </div>
                </div>

                <div class="row p-1">

                    <div class="col">
                        Retail price
                    </div>

                    <div class="col">
                        {% if good.retail_price %}
                        {{ good.retail_price }} ₼
                        {% else %}
                        ---
                        {% endif %}
                    </div>
                </div>

                <div class="row p-1">

                    <div class="col">
                        Market stock
                    </div>

                    <div class="col">
                        {% if good.store_hall or good.store_back or good.store_up %}
                        <div class="col">
                            {% if good.store_hall %}
                            {{ good.store_hall }}
                            {% endif %}
                        </div>
                        <div class="col">
                            {% if good.store_back %}
                            {{ good.store_back }}
                            {% endif %}
                        </div>
                        <div class="col">
                            {% if good.store_up %}
                            {{ good.store_up }}
                            {% endif %}
                        </div>
                        {% else %}
                        ---
                        {% endif %}
                    </div>
                </div>
            </div>
        </div></a>
        <hr class="border-black">
        {% endfor %}
        <div class="container">
            <div class="row p-1">
                <div class="col">
                    {% if page_obj.has_previous %}
                    <h2>
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
                    </h2>
                    {% endif %}
                </div>
                <div class="col">
                    {% if page_obj.has_next %}
                    <h2>
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
                    </h2>
                    {% endif %}
                </div>
            </div>
        </div>

    {% else %}
        <h2>Nothing found</h2>
    {% endif %}
</div>

{% endblock%}